package com.wesleyadiel.ai

import android.graphics.Bitmap

/**
 * Interface for interacting with a local multimodal LLM that supports image input.
 */
interface GemmaVisionClient {

    /**
     * Performs inference using a prompt and an input image.
     *
     * @param prompt The instruction or question for the model.
     * @param image The image to be processed by the model.
     * @return The raw output text generated by the model.
     */
    suspend fun infer(prompt: String, image: Bitmap): String
}