name: Android Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # Ex: v1.2.3

jobs:
  build:
    name: Build Release Bundle
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: keystore.jks
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode keystore inside /app
        run: echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 -d > app/keystore.jks

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab